version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - my_network
    restart: always
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    networks:
      - my_network

networks:
  my_network:
    driver: bridge